// Mocks generated by Mockito 5.3.2 from annotations
// in mobile_app/test/providers/api_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:built_collection/built_collection.dart' as _i11;
import 'package:built_value/serializer.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:openapi/src/api.dart' as _i8;
import 'package:openapi/src/api/categories_api.dart' as _i4;
import 'package:openapi/src/api/event_api.dart' as _i5;
import 'package:openapi/src/api/event_organizer_api.dart' as _i6;
import 'package:openapi/src/api/reservation_api.dart' as _i7;
import 'package:openapi/src/model/category.dart' as _i12;
import 'package:openapi/src/model/event.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSerializers_1 extends _i1.SmartFake implements _i3.Serializers {
  _FakeSerializers_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategoriesApi_2 extends _i1.SmartFake implements _i4.CategoriesApi {
  _FakeCategoriesApi_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventApi_3 extends _i1.SmartFake implements _i5.EventApi {
  _FakeEventApi_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventOrganizerApi_4 extends _i1.SmartFake
    implements _i6.EventOrganizerApi {
  _FakeEventOrganizerApi_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReservationApi_5 extends _i1.SmartFake
    implements _i7.ReservationApi {
  _FakeReservationApi_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_6<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Openapi].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenapi extends _i1.Mock implements _i8.Openapi {
  MockOpenapi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  _i3.Serializers get serializers => (super.noSuchMethod(
        Invocation.getter(#serializers),
        returnValue: _FakeSerializers_1(
          this,
          Invocation.getter(#serializers),
        ),
      ) as _i3.Serializers);
  @override
  void setOAuthToken(
    String? name,
    String? token,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setOAuthToken,
          [
            name,
            token,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setBearerAuth(
    String? name,
    String? token,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setBearerAuth,
          [
            name,
            token,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setBasicAuth(
    String? name,
    String? username,
    String? password,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setBasicAuth,
          [
            name,
            username,
            password,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setApiKey(
    String? name,
    String? apiKey,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setApiKey,
          [
            name,
            apiKey,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.CategoriesApi getCategoriesApi() => (super.noSuchMethod(
        Invocation.method(
          #getCategoriesApi,
          [],
        ),
        returnValue: _FakeCategoriesApi_2(
          this,
          Invocation.method(
            #getCategoriesApi,
            [],
          ),
        ),
      ) as _i4.CategoriesApi);
  @override
  _i5.EventApi getEventApi() => (super.noSuchMethod(
        Invocation.method(
          #getEventApi,
          [],
        ),
        returnValue: _FakeEventApi_3(
          this,
          Invocation.method(
            #getEventApi,
            [],
          ),
        ),
      ) as _i5.EventApi);
  @override
  _i6.EventOrganizerApi getEventOrganizerApi() => (super.noSuchMethod(
        Invocation.method(
          #getEventOrganizerApi,
          [],
        ),
        returnValue: _FakeEventOrganizerApi_4(
          this,
          Invocation.method(
            #getEventOrganizerApi,
            [],
          ),
        ),
      ) as _i6.EventOrganizerApi);
  @override
  _i7.ReservationApi getReservationApi() => (super.noSuchMethod(
        Invocation.method(
          #getReservationApi,
          [],
        ),
        returnValue: _FakeReservationApi_5(
          this,
          Invocation.method(
            #getReservationApi,
            [],
          ),
        ),
      ) as _i7.ReservationApi);
}

/// A class which mocks [EventApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventApi extends _i1.Mock implements _i5.EventApi {
  MockEventApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Response<_i10.Event>> addEvent({
    required String? title,
    required String? name,
    required int? freePlace,
    required int? startTime,
    required int? endTime,
    required String? latitude,
    required String? longitude,
    required _i11.BuiltList<int>? categories,
    String? placeSchema,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [],
          {
            #title: title,
            #name: name,
            #freePlace: freePlace,
            #startTime: startTime,
            #endTime: endTime,
            #latitude: latitude,
            #longitude: longitude,
            #categories: categories,
            #placeSchema: placeSchema,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<_i10.Event>>.value(
            _FakeResponse_6<_i10.Event>(
          this,
          Invocation.method(
            #addEvent,
            [],
            {
              #title: title,
              #name: name,
              #freePlace: freePlace,
              #startTime: startTime,
              #endTime: endTime,
              #latitude: latitude,
              #longitude: longitude,
              #categories: categories,
              #placeSchema: placeSchema,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<_i10.Event>>);
  @override
  _i9.Future<_i2.Response<void>> cancelEvent({
    required String? id,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelEvent,
          [],
          {
            #id: id,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<void>>.value(_FakeResponse_6<void>(
          this,
          Invocation.method(
            #cancelEvent,
            [],
            {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<void>>);
  @override
  _i9.Future<_i2.Response<_i11.BuiltList<_i10.Event>>> getByCategory({
    required int? categoryId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCategory,
          [],
          {
            #categoryId: categoryId,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<_i11.BuiltList<_i10.Event>>>.value(
            _FakeResponse_6<_i11.BuiltList<_i10.Event>>(
          this,
          Invocation.method(
            #getByCategory,
            [],
            {
              #categoryId: categoryId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<_i11.BuiltList<_i10.Event>>>);
  @override
  _i9.Future<_i2.Response<_i10.Event>> getEventById({
    required int? id,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [],
          {
            #id: id,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<_i10.Event>>.value(
            _FakeResponse_6<_i10.Event>(
          this,
          Invocation.method(
            #getEventById,
            [],
            {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<_i10.Event>>);
  @override
  _i9.Future<_i2.Response<_i11.BuiltList<_i10.Event>>> getEvents({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvents,
          [],
          {
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<_i11.BuiltList<_i10.Event>>>.value(
            _FakeResponse_6<_i11.BuiltList<_i10.Event>>(
          this,
          Invocation.method(
            #getEvents,
            [],
            {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<_i11.BuiltList<_i10.Event>>>);
  @override
  _i9.Future<_i2.Response<_i11.BuiltList<_i10.Event>>> getMyEvents({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyEvents,
          [],
          {
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<_i11.BuiltList<_i10.Event>>>.value(
            _FakeResponse_6<_i11.BuiltList<_i10.Event>>(
          this,
          Invocation.method(
            #getMyEvents,
            [],
            {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<_i11.BuiltList<_i10.Event>>>);
  @override
  _i9.Future<_i2.Response<void>> patchEvent({
    required String? id,
    _i10.Event? event,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchEvent,
          [],
          {
            #id: id,
            #event: event,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<void>>.value(_FakeResponse_6<void>(
          this,
          Invocation.method(
            #patchEvent,
            [],
            {
              #id: id,
              #event: event,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<void>>);
}

/// A class which mocks [CategoriesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesApi extends _i1.Mock implements _i4.CategoriesApi {
  MockCategoriesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Response<_i12.Category>> addCategories({
    required String? categoryName,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategories,
          [],
          {
            #categoryName: categoryName,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<_i12.Category>>.value(
            _FakeResponse_6<_i12.Category>(
          this,
          Invocation.method(
            #addCategories,
            [],
            {
              #categoryName: categoryName,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<_i12.Category>>);
  @override
  _i9.Future<_i2.Response<_i11.BuiltList<_i12.Category>>> getCategories({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
          {
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i9.Future<_i2.Response<_i11.BuiltList<_i12.Category>>>.value(
                _FakeResponse_6<_i11.BuiltList<_i12.Category>>(
          this,
          Invocation.method(
            #getCategories,
            [],
            {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<_i11.BuiltList<_i12.Category>>>);
}
