name: Flutter_Android

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java to compile Android project
        uses: actions/setup-java@v2
        with:
         distribution: 'zulu'
         java-version: '11'

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.10.0'

      - name: Restore packages
        run: flutter pub get

      - name: Build Android apk
        run: flutter build apk
        
      - name: Build Android appbundle
        run: flutter build appbundle
      
      - name: Run tests
        run: flutter test
