name: Flutter_Android

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java to compile Android project
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.0.1'

      - name: Restore packages
        run: flutter pub get

      - name: Build Android App Bundle
        run: flutter build appbundle --release
